openapi: 3.0.0
info:
  title: Messages API
  version: 1.0.0
paths:
  /messages:
    get:
      summary: Get Messages
      description: Retrieves a list of messages.
      parameters:
        - name: status
          in: query
          description: Filter messages by status
          required: false
          schema:
            type: "string"
            enum:
              - "sent"
              - "read"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageListResponse'
                type: "object"
                properties:
                  messages:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        uuid: 
                          type: "string"
                        text:
                          type: "string"
                        status:
                          type: "string"
                          enum:
                            - "sent"
                            - "read"
              example:
                messages:
                  - text: "Hello, World!"
                    status: "read"
                  - text: "How are you today?"
                    status: "sent"
                  - text: "Thanks, I'm fine. How about you?"
                    status: "sent"
    post:
      summary: Adds a Message
      parameters:
        -   name: text
            in: query
            description: The text you want to send
            required: true
            schema:
              type: "string"
      responses:
        '204':
          description: Successfully sent
components:
  schemas:
    Message:
      type: object
      properties:
        uuid:
          type: string
        text:
          type: string
        status:
          type: string
          enum:
            - sent
            - read
    MessageListResponse:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
      example:
        messages:
          - uuid: "1ef45346-c7fd-62cc-b70d-99e50374d1bb"
            text: "Hello, World!"
            status: "read"
          - uuid: "1ef4534f-09f7-6b70-87b3-fb8ae977795c"
            text: "How are you today?"
            status: "sent"
          - uuid: "1ef4535d-b5d6-66e0-9368-5daa614746b9"
            text: "Thanks, I'm fine. How about you?"
            status: "sent"